# Generated by Django 6.0.4 on 2026-05-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='utf8mb3_bin', max_length=45, unique=True)),
                ('parent_id', models.IntegerField()),
                ('sort_order_index', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'task_categories',
                'ordering': ['sort_order_index'],
            },
        ),
        migrations.CreateModel(
            name='TaskPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('color_code', models.CharField(blank=True, max_length=45, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'task_priorities',
                'ordering': ['weight'],
            },
        ),
        migrations.CreateModel(
            name='TaskRepeatFrequencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'task_repeat_frequency_types',
            },
        ),
        migrations.CreateModel(
            name='TaskRepeatOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'task_repeat_options',
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('color_code', models.CharField(blank=True, max_length=45, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'task_statuses',
            },
        ),
    ]
