# Generated by Django 6.0.4 on 2026-05-04 15:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="target_account",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="transaction_type",
        ),
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="direction",
            field=models.CharField(
                choices=[("CREDIT", "Credit"), ("DEBIT", "Debit")],
                default="CREDIT",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reference_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="mode",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.transactionmode",
            ),
        ),
    ]
