# Generated by Django 5.2.8 on 2026-05-05 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
        ('transactions', '0002_transactionmode_remove_transaction_target_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='bank_accounts.bank_account'),
        ),
    ]
