# Generated by Django 5.2.8 on 2026-05-05 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0002_remove_bank_account_acc_no_and_more'),
        ('transactions', '0003_account_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bank_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_no', to='bank_accounts.bank_account'),
        ),
    ]
