# Generated by Django 5.2.8 on 2026-05-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_account_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmode',
            name='name',
            field=models.CharField(choices=[('UPI', 'UPI'), ('NEFT', 'NEFT'), ('CASH', 'Cash'), ('IMPS', 'IMPS'), ('RTGS', 'RTGS')], max_length=50, unique=True),
        ),
    ]
