# Generated by Django 5.2.8 on 2026-05-05 10:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transactionmode_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transactionmode', to_field='name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
