# Generated by Django 5.2.8 on 2026-05-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('acc_no', models.CharField(max_length=12)),
                ('account_type', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=12)),
                ('branch', models.CharField(max_length=100)),
            ],
        ),
    ]
