# Generated by Django 5.2.8 on 2026-05-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_account',
            name='acc_no',
        ),
        migrations.AddField(
            model_name='bank_account',
            name='account_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bank_account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
