# Generated by Django 5.2.8 on 2026-05-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0002_remove_bank_account_acc_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_account',
            name='account_number',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
